config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :home, only:[:index]
  resources :test, only:[:index,:update]
  resources :login, only:[:index,:create,:destroy]
  resources :register, only:[:index,:create]
  resources :profile, except:[:destroy,:new,:edit]
  resources :chat
  resources :message
  resources :activities, only: [:create]
  mount ActionCable.server => '/cable'


post '/user/personality' => 'users#personality'
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_and_belongs_to_many :users
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/personality.rb
class Personality < ApplicationRecord
  has_one :result
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  has_many :personalities, -> { order(score: :desc) }, dependent: :destroy
  has_many :traits
end

app/models/trait.rb
class Trait < ApplicationRecord
  has_one :result
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name,presence: true
  has_one :result, dependent: :destroy
  has_and_belongs_to_many :activities, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  #before_action { @user = User.find(session[:user_id]) }

  def create

    # redirect '/profiles/2'
    # params gives us the activiy id's that the user selected
    listOfActivities = params["activity"].map{|k, v| v}

    activityList = Activity.where(id: listOfActivities)
    # Create activites for a user
    @user = User.find(session[:user_id])
    @user.activities << activityList

  end
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    @personalities = ['Thoughtful','Rational','Reliable', 'Mellow', 'Social','Charismatic','Adventurous']
    @userPtype = User.find(session[:user_id]).result.personalities.first
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @user = User.new
  end

  def log_in(user)
    session[:user_id] = user.id
    redirect_to test_index_path, notice: 'Logged in'
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)
    if user && user.authenticate(params[:login][:password])
      log_in user
    else
      redirect_to :back, notice: 'couldnt log in'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def index
    @user = User.find(session[:user_id])
    if @user.result
      @traitify = Traitify.new
      @assessment = @traitify.find_results(@user.result.assessment_id)
      @traits = @user.result.traits.first
      @matches = get_matches
      @activities = Activity.all()
      @user = User.find(session[:user_id])
    else
      redirect_to test_index_path
    end
  end
  
  def get_matches
    return User.includes(result: [:personalities,:traits]).where('traits.name=? or personality=?',@traits.name, @user.result.personalities.first.name).references(:personalities,:traits)
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  def index
  end

  def log_in(user)
    session[:user_id] = user.id
    redirect_to test_index_path, notice: 'Logged in'
  end

  def create
    @user = User.new(register_params)
    if @user.save
      user = User.where(:email => params[:register][:email].downcase).first
      log_in user
    else
        redirect_to :back, notice: 'couldnt log in'
    end
  end
  private
  def register_params
    params.require(:register).permit(
      :name,
      :email,
      :password
    )
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    traitify = Traitify.new
    user = User.find(session[:user_id])
    if(!user.result)
      @assessment = traitify.create_assessment(deck_id: 'core')
    else
      redirect_to profile_index_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def personality
    traitify = Traitify.new
    user = User.find(session[:user_id])
    r = traitify.find_results(params[:id])
    user.update({personality:r.personality_types.first.personality_type.name})
    user.save
    result = Result.new
    result.user_id = user.id
    result.assessment_id = params[:id]
    result.image = r.personality_types.first.personality_type.badge.image_small
    result.save
    r.personality_types.each do |ptype|
    Personality.create({
     result_id: result.id,
     name: ptype.personality_type.name,
     score: ptype.score,
    })
    end
    Trait.create({
      result_id: result.id,
      name: traitify.raw_personality_traits(params[:id]).first.personality_trait.name
    })
    redirect_to profile_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
      @current_user ||= User.find_by_id(session[:user])
  end

  def signed_in?
       @current_user != nil
  end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
  def assessment_css(assessment)
    puts assessment
    case assessment.result.personalities.first.name
      when "Mellow"
        return "mellowType"
      when "Social"
        return "socialType"
      when "Charismatic"
        return "charismaticType"
      when "Adventurous"
        return "adventureType"
      when "Rational"
        return "rationalType"
      when "Thoughtful"
        return "thoughtfulType"
      when "Reliable"
        return "reliableType"
      else
        return ''
    end
  end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/chat/_messages.html.erb
<% if @messages %>
<div id='messages'>
  <% @messages.each do |message| %>
    <%= img_tag User.find(message.user_id).result.image %>
    <p><%= message.body %></p>
  <%end%>
</div>
<%end%>

app/views/chat/index.html.erb
<div class="loginContainer chatWrap">
  <header>
    <div class="circles">
        <span class="circle"></span>
        <span class="circle"></span>
        <span class="circle"></span>
      </div>
      <%= image_tag('chat.png') %>
  </header>
  <h2>Chat</h2>
  <div class="messageArea loginForm">
    <section id='messages'></section>
    <div class="userInput">
      <textarea name='message'></textarea>
    </div>
    <div class="chatButton">
      <button>Send</button>
    </div>

  </div>
</div>
<div class='channelGroup'>
  <% @personalities.each do |personality| %>
    <button class='<%=personality%>Channel' name='<%=personality%>'><%=personality%></button>
  <%end%>
</div>
<script>
  $(document).ready(function(){
    MakeChannel('<%=@userPtype.name%>','<%=session[:user_id]%>')
    $('.chatButton>button').on('click',function(e){
      if($('textarea').val() !== ''){
        e.preventDefault()
        App.chat.speak($('textarea').val())
        $('textarea').val('')
      }
    })
    $('textarea').keyup(function(e){
      if(e.which === 13 && $('textarea').val() !== ''){
        App.chat.speak($('textarea').val())
        $('textarea').val('')
      }
    })
    $('.channelGroup>button').on('click',function(e){
      e.preventDefault()
      MakeChannel(e.target.name,'<%=session[:user_id]%>')
      $('textarea').val('')
    })
  });
  </script>

app/views/chat/show.html.erb
<div class="loginContainer chatWrap">
  <header>
    <div class="circles">
        <span class="circle"></span>
        <span class="circle"></span>
        <span class="circle"></span>
      </div>
      <%= image_tag('chat.png') %>
  </header>
    <h2>Chat</h2>
  <div class="messageArea loginForm">
  <section id='messages'></section>
  <div class="userInput">
    <textarea name='message'></textarea>
  </div>
  <div class="chatButton">
    <button>Send</button>
  </div>
  </div>
</div>



  <script>
    $('button').on('click',function(e){
      e.preventDefault()
      $('#messages').append($('textarea').val())
      $('textarea').val('')
    })
  </script>

app/views/home/index.html.erb
<div class="wrapper">
  <div class="box register">
    <p> 1. Register </p>
    <%= image_tag('sign-up.png') %>
  </div>
  <div class="box takeTest">
    <p> 2. Personality Test </p>
    <%= image_tag('pTest.png') %>
  </div>
  <div class="box chooseActivities">
    <p> 3. Choose Activities </p>
    <%= image_tag('chooseActivities.png') %>
  </div>
  <div class="box getMatches">
    <p> 4. Get Matches </p>
    <%= image_tag('friendsBlue.png') %>
  </div>

</div>

<div id="modal">
    <!-- modal box content -->
    <div class="register">
        <h2>Register</h2>

      <%= form_for :register, url: register_index_path, method: :post do |f| %>

      <div class="field">
        <%= f.label :name %><br />
        <%= f.text_field :name, autofocus: true %>
      </div>


      <div class="field">
        <%= f.label :email %><br />
        <%= f.email_field :email, autofocus: true %>
      </div>

      <div class="field">
        <%= f.label :password, "Password" %><br />
        <%= f.password_field :password, autofocus: true, autocomplete: "off" %>
      </div>

      <%= f.submit "Register"%>

    <% end %>
  </div>

</div>

app/views/login/index.html.erb
<div class="wrapper loginWrapper">
  <div class="loginContainer">
    <header>
      <div class="circles">
        <span class="circle"></span>
        <span class="circle"></span>
        <span class="circle"></span>
      </div>
      <%= image_tag('tinyLogo.png') %>
    </header>
      <h2>Login</h2>
    <div class="loginForm">

      <%= form_for :login, url: login_index_path do |f| %>

        <div class="field">
          <%= f.label :email %><br />
          <%= f.email_field :email, autofocus: false %>
        </div>

        <div class="field">
          <%= f.label :password, "Password" %><br />
          <%= f.password_field :password, autofocus: false, autocomplete: "off" %>
        </div>


        <%= f.submit "Login", method: :post %>


      <% end %>
      </div>
      </div>
</div>

app/views/register/index.html.erb
<h2>Register</h2>

<%= form_for :register, url: register_index_path do |f| %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name, autofocus: true %>
  </div>


  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true %>
  </div>

  <div class="field">
    <%= f.label :password, "Password" %><br />
    <%= f.password_field :password, autofocus: true, autocomplete: "off" %>
  </div>

  <%= f.submit "Register", method: :post %>

<% end %>