config/routes.rb
Rails.application.routes.draw do
  root to: 'home#index'
  resources :home, only:[:index]
  resources :test, only:[:index,:update]
  resources :login, only:[:index,:create,:destroy]
  resources :register, only:[:index,:create]
  resources :profile, except:[:destroy,:new,:edit]
  resources :chat
  resources :message
  resources :activities, only: [:create]
  mount ActionCable.server => '/cable'


post '/user/personality' => 'users#personality'
end

app/models/activity.rb
class Activity < ApplicationRecord
  has_and_belongs_to_many :users
  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  after_create_commit { MessageBroadcastJob.perform_later self }
end

app/models/personality.rb
class Personality < ApplicationRecord
  has_one :result
end

app/models/result.rb
class Result < ApplicationRecord
  belongs_to :user
  has_many :personalities, -> { order(score: :desc) }, dependent: :destroy
  has_many :traits
end

app/models/trait.rb
class Trait < ApplicationRecord
  has_one :result
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :name,presence: true
  has_one :result, dependent: :destroy
  has_and_belongs_to_many :activities, dependent: :destroy
  has_many :messages, dependent: :destroy
end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
  def index
    @personalities = ['Thoughtful','Rational','Reliable', 'Mellow', 'Social','Charismatic','Adventurous']
    @userPtype = User.find(session[:user_id]).result.personalities.first
    
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  def index
    @user = User.new
  end

  def log_in(user)
    session[:user_id] = user.id
    redirect_to test_index_path, notice: 'Logged in'
  end

  def create
    user = User.find_by(email: params[:login][:email].downcase)
    if user && user.authenticate(params[:login][:password])
      log_in user
    else
      redirect_to :back, notice: 'couldnt log in'
    end
  end
  def destroy
    session[:user_id] = nil
    redirect_to :root
  end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController

  def index
    @user = User.find(session[:user_id])
    if @user.result
      @traitify = Traitify.new
      @assessment = @traitify.find_results(@user.result.assessment_id)
      @traits = @user.result.traits.first
      @matches = get_matches
      @activities = Activity.all()
      @user = User.find(session[:user_id])
    else
      redirect_to test_index_path
    end
  end
  
  def get_matches
    return User.includes(result: [:personalities,:traits]).where('traits.name=? or personality=?',@traits.name, @user.result.personalities.first.name).references(:personalities,:traits)
  end
end

app/controllers/test_controller.rb
class TestController < ApplicationController
  def index
    traitify = Traitify.new
    user = User.find(session[:user_id])
    if(!user.result)
      @assessment = traitify.create_assessment(deck_id: 'core')
    else
      redirect_to profile_index_path
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def personality
    traitify = Traitify.new
    user = User.find(session[:user_id])
    r = traitify.find_results(params[:id])
    user.update({personality:r.personality_types.first.personality_type.name})
    user.save
    result = Result.new
    result.user_id = user.id
    result.assessment_id = params[:id]
    result.image = r.personality_types.first.personality_type.badge.image_small
    result.save
    r.personality_types.each do |ptype|
    Personality.create({
     result_id: result.id,
     name: ptype.personality_type.name,
     score: ptype.score,
    })
    end
    Trait.create({
      result_id: result.id,
      name: traitify.raw_personality_traits(params[:id]).first.personality_trait.name
    })
    redirect_to profile_index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
      @current_user ||= User.find_by_id(session[:user])
  end

  def signed_in?
       @current_user != nil
  end
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
  def assessment_css(assessment)
    puts assessment
    case assessment.result.personalities.first.name
      when "Mellow"
        return "mellowType"
      when "Social"
        return "socialType"
      when "Charismatic"
        return "charismaticType"
      when "Adventurous"
        return "adventureType"
      when "Rational"
        return "rationalType"
      when "Thoughtful"
        return "thoughtfulType"
      when "Reliable"
        return "reliableType"
      else
        return ''
    end
  end
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/test_helper.rb
module TestHelper
end

app/views/layouts/_footer.html.erb
<footer>

 <div class="footerText">

  </div>

  <div class="social">
    <%= image_tag("fbIcon.png") %>
    <%= image_tag("twitterIcon.png") %>
    <%= image_tag("pinterestIcon.png") %>
  </div>


</footer>

app/views/layouts/_top_nav.html.erb
<nav class="<%= yield :nav_assessment_class %>" >

  <%= link_to image_tag("whiteLogo.png"), root_path %>

  <div class="links">
  <% if session[:user_id] %>
  <%= link_to 'Chat', chat_index_path %>
  <%= link_to 'Profile', profile_index_path%>
  <%= link_to 'Logout', login_path(session[:user_id]), method: :delete %>
  <%else%>
  <%= link_to 'Login', login_index_path %>
  <%end%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Purely Platonic</title>
  <script src='https://cdn.traitify.com/js/widgets/v1.js'></script>
  <link href="https://fonts.googleapis.com/css?family=Montserrat|Roboto" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application' %>
</head>

  <body>
     <%= render 'layouts/top_nav' %>
    <%= yield %>
     <%= render 'layouts/footer' %>
  </body>
</html>